name: artifacts

on: 
    push:
        branches:
            - master

jobs:
    artifactss:
        runs-on: ubuntu-latest
        steps:
            - name: generate report
              run: |
                 echo "hello world" >> file.txt
                 echo "kyaa baat hai" >> file.txt
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                path: file.txt
    download-artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: download report
              uses: actions/download-artifact@v4
              with:
                path: file.txt
            - run: cat file.txt