name: cache-demo

on: push

jobs:
    script:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install
              run: pip install -r requirements.txt
            
            - name: fails
              run: |
                 if [ -x "$(command -v docker)" ]; then
                     exit 1
                 else
                    echo "Install docker"...
#   cache-job:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Cache node modules
#         uses: actions/cache@v4
#         with:
#           path: ~/.npm
#           key: npm-cache-${{ hashFiles('package-lock.json') }}

#       - name: Install dependencies
#         run: npm install