name: cache

on: 
    push:
        branches:
            - master

jobs:
    cached:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
        
            - name: Cache node modules
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-cache-${{ hashFiles('package-lock.json') }}

            - name: install dependencies
              run: npm install