name: docker integration
on: 
    push:
        branches:
            - master
jobs:
    build-Push:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout 
              uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build and push
              uses: docker/build-push-action@v6
              with: 
                context: .
                push: true
                tags: |
                 ${{ vars.DOCKERHUB_USER}}/github-actions:${{ github.ref_name}}
                  ${{ vars.DOCKERHUB_USER}}/github-actions:latest
