name: environment practices
env:
    APP_NAME: myApp

on: 
    workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest
    env: 
        name: staging
    steps: 
      - name: version 1
        env:
            version: "1.0.0"
        run: |
         echo ${APP_NAME}
         echo ${name}
         echo ${version}
         echo ${{ github.actor }}
         echo ${{ github.sha }}