name: OS informations
on: 
    push:
        branches:
            - master
jobs:
  osInfo:
      strategy:
         fail-fast: false
         matrix:
            os: ["ubuntu-latest" ,"windows-latest","macos-latest"]
      runs-on: ${{ matrix.os }}
      steps:
        - name: name of OS
          id: step1
          run: echo "${{runner.os}}"
        - name: check hostname of Running os
          run: hostname
        - name: current user name
          run: |
             echo "User:"
             whoami