name: package checker

on: 
    # push:
    #     branches: 
    #         - master
    workflow_dispatch:

jobs:
    packageChecker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ["docker","git","node","python"]
        steps:
            - name: ${{ matrix.package }} check
              run: ${{matrix.package}} --version

