name: secrets 

on:
    push:
        branches: 
            - master

jobs:
    secret-printer:
        runs-on: ubuntu-latest
        steps:
            - name: secret checker
              env:
                DOCKER_PASS: ${{secrets.DOCKERHUB_TOKEN}}
                DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
              run: |
                if [ -n "$DOCKER_PASS" ] && [-n "$DOCKER_USER"]; then
                   echo "variable are set successfully"
                else
                    echo "not set"
                fi
        # steps:
        #     - name: secret printer
        #       run: echo "${{secrets.MY_SECRET_MESSAGE}}"
        #       env:
        #         MY_MESSAGE: ${{secrets.MY_SECRET_MESSAGE}} 
        #     - name: print true if setted
        #       run: |
        #         if [ -n "$MY_MESSAGE"]; then
        #            echo "secret is set"
        #         else
        #            echo "secret is not set"
        #         fi