name: secrets 

on:
    push:
        branches: 
            - master

jobs:
    secret-printer:
        runs-on: ubuntu-latest
        steps:
            - name: secret printer
              run: echo "${{secrets.MY_SECRET_MESSAGE}}"