name: self hosting runner

on: 
    workflow_dispatch:
jobs:
    selfhoster:
        runs-on: [self-hosted, my-runner]
        steps:
         - name: Host Name
           run: hostname
         
         - name: working directory
           run: pwd
        
         - name: create file 
           run : |
             echo "this is the test file" > file.txt
             echo "file created : file.txt"

         - name: verfiy 
           run: |
             if [ -f "file.txt" ]; then
                echo "file exists"
             else
                echo "doesnot exists"
             fi

        